### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by raymclee** [quietboil/sibyl#7]
Hi, I got segmentation fault error following the nonblocking example when I build in release mode (cargo build -r). 
cargo run and cargo build work fine.

**Comment by raymclee** [comment]
And if I change the runtime to tokio from actix, I got below error.
`
   |
35 |     tokio_rt::runtime::Builder::new_multi_thread().enable_all().build().unwrap().block_on(future)
   |                                 ^^^^^^^^^^^^^^^^ function or associated item not found in tokio::runtime::Builder
`

**Comment by quietboil** [comment]
I have reproduced it with tokio:
```sh
cargo run --example async_readme --features nonblocking,tokio --release
```
Try `cargo clean` the `target`. it probably is not recompiling something that it should.

**Comment by raymclee** [comment]
> I have reproduced it with tokio:
> 
> ```shell
> cargo run --example async_readme --features nonblocking,tokio --release
> ```
> 
> Try `cargo clean` the `target`. it probably is not recompiling something that it should.

it says "one of the selected packages contains these features: nonblocking, tokio"

**Comment by quietboil** [comment]
There is not enough context to help you there. Where and how are you running it? Is this from a cloned repository? There how I executed that command trying to reproduce the issue:
```sh
git clone https://github.com/quietboil/sibyl.git
cd sibyl
cargo run --example async_readme --features nonblocking,tokio --release
```

**Comment by raymclee** [comment]
> There is not enough context to help you there. Where and how are you running it? Is this from a cloned repository? There how I executed that command trying to reproduce the issue:
> 
> ```shell
> git clone https://github.com/quietboil/sibyl.git
> cd sibyl
> cargo run --example async_readme --features nonblocking,tokio --release
> ```

I created a new project and add sibyl as dependencies. I run fine with actix runtime for nonblocking. But when i build release, I got segmentation fault error.
If i change the change the feature to tokio from actix it cannot compile.
just tried clone the repo and it can compile but got the same error "segmentation fault".
I'm connecting to oracle cloud database btw.

**Comment by quietboil** [comment]
Here's what I see thus far - it works at `opt-level` 0 and 1. All others include some optimization that (maybe) makes Sibyl pass unexpected arguments to OCI. It'll take some time to find what is throwing it off. Until I address this, you could try this workaround (the following `Cargo.toml` is from the test project I created to test the workaround - a simple binary crate where `main.rs` is a copy of `main()` from `sibyl/examples/async_readme.rs`):
```toml
[package]
name = "async_readme"
version = "0.1.0"
edition = "2021"

[dependencies]
sibyl = {version = "0.6", features = ["nonblocking", "tokio"]}
tokio = {version = "1", features = ["full"]}

[profile.release.package.sibyl]
opt-level = 1

[profile.release.package."*"]
opt-level = 3

[profile.release]
# This is also important
opt-level = 1
```
